HDFIO_VERSION = "1.0-0"

INTERNAL_ERROR = "internal error - something we thought was impossible happened. Please report this to the package developers https://github.com/RBigData/hdfio/issues"
